# Generated by Django 4.2.3 on 2023-07-07 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0002_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
