# Generated by Django 4.2.3 on 2023-07-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Customer', '0004_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='orderr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
            preserve_default=False,
        ),
    ]
