# Generated by Django 4.2.3 on 2023-07-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='orderrs',
            field=models.ManyToManyField(to='Order.order'),
        ),
    ]
