# Generated by Django 4.2.3 on 2023-07-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_vendor_product_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Vendor',
        ),
    ]
