# Generated by Django 4.2.2 on 2023-06-18 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField()),
                ('total', models.IntegerField()),
                ('number_of_products', models.IntegerField()),
                ('shipping_cost', models.FloatField()),
                ('Payment_options', models.TextField()),
                ('discounts', models.FloatField()),
            ],
        ),
    ]
