# Generated by Django 4.2.3 on 2023-07-10 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
        ('Cart', '0004_cart_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='orderrr',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Order.order'),
        ),
    ]
